import 'package:flutter/widgets.dart';

extension AppText on BuildContext {
  String tr(String english, String vietnamese) {
    final code = Localizations.localeOf(this).languageCode;
    if (code == 'vi') return vietnamese;
    if (code == 'en') return english;
    return _translations[english]?[code] ?? english;
  }
}

const _translations = <String, Map<String, String>>{
  'Today': {
    'es': 'Hoy',
    'fr': "Aujourd’hui",
    'zh': '今天',
    'hi': 'आज',
    'ar': 'اليوم'
  },
  'Summary': {
    'es': 'Resumen',
    'fr': 'Résumé',
    'zh': '总结',
    'hi': 'सारांश',
    'ar': 'الملخص'
  },
  'Details': {
    'es': 'Detalles',
    'fr': 'Détails',
    'zh': '详情',
    'hi': 'विवरण',
    'ar': 'التفاصيل'
  },
  'Eaten': {
    'es': 'Consumido',
    'fr': 'Consommé',
    'zh': '已摄入',
    'hi': 'खाया',
    'ar': 'المتناول'
  },
  'Remaining': {
    'es': 'Restante',
    'fr': 'Restant',
    'zh': '剩余',
    'hi': 'शेष',
    'ar': 'المتبقي'
  },
  'Burned': {
    'es': 'Quemado',
    'fr': 'Brûlé',
    'zh': '已消耗',
    'hi': 'जली कैलोरी',
    'ar': 'المحروق'
  },
  'Nutrition': {
    'es': 'Nutrición',
    'fr': 'Nutrition',
    'zh': '营养',
    'hi': 'पोषण',
    'ar': 'التغذية'
  },
  'More': {'es': 'Más', 'fr': 'Plus', 'zh': '更多', 'hi': 'और', 'ar': 'المزيد'},
  'Breakfast': {
    'es': 'Desayuno',
    'fr': 'Petit-déjeuner',
    'zh': '早餐',
    'hi': 'नाश्ता',
    'ar': 'الإفطار'
  },
  'Lunch': {
    'es': 'Almuerzo',
    'fr': 'Déjeuner',
    'zh': '午餐',
    'hi': 'दोपहर का भोजन',
    'ar': 'الغداء'
  },
  'Dinner': {
    'es': 'Cena',
    'fr': 'Dîner',
    'zh': '晚餐',
    'hi': 'रात का खाना',
    'ar': 'العشاء'
  },
  'Snacks': {
    'es': 'Tentempiés',
    'fr': 'Collations',
    'zh': '零食',
    'hi': 'नाश्ता',
    'ar': 'وجبات خفيفة'
  },
  'Fasting': {
    'es': 'Ayuno',
    'fr': 'Jeûne',
    'zh': '禁食',
    'hi': 'उपवास',
    'ar': 'الصيام'
  },
  'Go to Fasting': {
    'es': 'Ir al ayuno',
    'fr': 'Ouvrir le jeûne',
    'zh': '进入禁食',
    'hi': 'उपवास खोलें',
    'ar': 'ابدأ الصيام'
  },
  'Water': {'es': 'Agua', 'fr': 'Eau', 'zh': '饮水', 'hi': 'पानी', 'ar': 'الماء'},
  'Activities': {
    'es': 'Actividades',
    'fr': 'Activités',
    'zh': '活动',
    'hi': 'गतिविधियाँ',
    'ar': 'الأنشطة'
  },
  'Search': {
    'es': 'Buscar',
    'fr': 'Rechercher',
    'zh': '搜索',
    'hi': 'खोजें',
    'ar': 'بحث'
  },
  'Camera': {
    'es': 'Cámara',
    'fr': 'Caméra',
    'zh': '相机',
    'hi': 'कैमरा',
    'ar': 'الكاميرا'
  },
  'Barcode': {
    'es': 'Código de barras',
    'fr': 'Code-barres',
    'zh': '条形码',
    'hi': 'बारकोड',
    'ar': 'الباركود'
  },
  'Voice/Text': {
    'es': 'Voz/Texto',
    'fr': 'Voix/Texte',
    'zh': '语音/文字',
    'hi': 'आवाज़/पाठ',
    'ar': 'صوت/نص'
  },
  'Search food online': {
    'es': 'Buscar alimentos en línea',
    'fr': 'Rechercher des aliments',
    'zh': '在线搜索食物',
    'hi': 'खाना ऑनलाइन खोजें',
    'ar': 'ابحث عن الطعام'
  },
  'Settings': {
    'es': 'Ajustes',
    'fr': 'Paramètres',
    'zh': '设置',
    'hi': 'सेटिंग्स',
    'ar': 'الإعدادات'
  },
  'Preferences': {
    'es': 'Preferencias',
    'fr': 'Préférences',
    'zh': '偏好设置',
    'hi': 'प्राथमिकताएँ',
    'ar': 'التفضيلات'
  },
  'Language': {
    'es': 'Idioma',
    'fr': 'Langue',
    'zh': '语言',
    'hi': 'भाषा',
    'ar': 'اللغة'
  },
  'Active': {
    'es': 'Activo',
    'fr': 'Actif',
    'zh': '活跃',
    'hi': 'सक्रिय',
    'ar': 'نشط'
  },
  'Green Days': {
    'es': 'Días verdes',
    'fr': 'Jours verts',
    'zh': '达标日',
    'hi': 'ग्रीन दिन',
    'ar': 'أيام الالتزام'
  },
  'Weight': {
    'es': 'Peso',
    'fr': 'Poids',
    'zh': '体重',
    'hi': 'वज़न',
    'ar': 'الوزن'
  },
  'Share Your Success': {
    'es': 'Comparte tu progreso',
    'fr': 'Partagez vos progrès',
    'zh': '分享你的进步',
    'hi': 'अपनी प्रगति साझा करें',
    'ar': 'شارك إنجازك'
  },
  'View day details': {
    'es': 'Ver detalles del día',
    'fr': 'Voir les détails du jour',
    'zh': '查看每日详情',
    'hi': 'दिन का विवरण देखें',
    'ar': 'عرض تفاصيل اليوم'
  },
  'Diary': {
    'es': 'Diario',
    'fr': 'Journal',
    'zh': '日记',
    'hi': 'डायरी',
    'ar': 'يومياتي'
  },
  'Recipes': {
    'es': 'Recetas',
    'fr': 'Recettes',
    'zh': '食谱',
    'hi': 'रेसिपी',
    'ar': 'الوصفات'
  },
  'Profile': {
    'es': 'Perfil',
    'fr': 'Profil',
    'zh': '个人资料',
    'hi': 'प्रोफ़ाइल',
    'ar': 'الملف الشخصي'
  },
  'Pro': {'es': 'Pro', 'fr': 'Pro', 'zh': '专业版', 'hi': 'प्रो', 'ar': 'برو'},
  'Calories': {
    'es': 'Calorías',
    'fr': 'Calories',
    'zh': '卡路里',
    'hi': 'कैलोरी',
    'ar': 'السعرات'
  },
  'Carbs': {
    'es': 'Carbohidratos',
    'fr': 'Glucides',
    'zh': '碳水',
    'hi': 'कार्ब्स',
    'ar': 'الكربوهيدرات'
  },
  'Protein': {
    'es': 'Proteína',
    'fr': 'Protéines',
    'zh': '蛋白质',
    'hi': 'प्रोटीन',
    'ar': 'البروتين'
  },
  'Fat': {
    'es': 'Grasa',
    'fr': 'Lipides',
    'zh': '脂肪',
    'hi': 'वसा',
    'ar': 'الدهون'
  },
  'Goal': {
    'es': 'Objetivo',
    'fr': 'Objectif',
    'zh': '目标',
    'hi': 'लक्ष्य',
    'ar': 'الهدف'
  },
  'Meals': {
    'es': 'Comidas',
    'fr': 'Repas',
    'zh': '餐食',
    'hi': 'भोजन',
    'ar': 'الوجبات'
  },
  'Nutrition facts': {
    'es': 'Datos nutricionales',
    'fr': 'Valeurs nutritionnelles',
    'zh': '营养信息',
    'hi': 'पोषण तथ्य',
    'ar': 'حقائق التغذية'
  },
  'Track now': {
    'es': 'Registrar ahora',
    'fr': 'Suivre maintenant',
    'zh': '立即记录',
    'hi': 'अभी ट्रैक करें',
    'ar': 'سجّل الآن'
  },
  'Add more': {
    'es': 'Añadir más',
    'fr': 'Ajouter plus',
    'zh': '继续添加',
    'hi': 'और जोड़ें',
    'ar': 'أضف المزيد'
  },
  'Welcome to recipes!': {
    'es': '¡Bienvenido a las recetas!',
    'fr': 'Bienvenue dans les recettes !',
    'zh': '欢迎来到食谱！',
    'hi': 'रेसिपी में आपका स्वागत है!',
    'ar': 'مرحبًا بك في الوصفات!',
  },
  'Transform your cooking experience into a delightful and rewarding adventure.': {
    'es':
        'Convierte tu experiencia culinaria en una aventura divertida y gratificante.',
    'fr':
        'Transformez votre cuisine en une aventure agréable et enrichissante.',
    'zh': '让烹饪体验成为愉快而有收获的旅程。',
    'hi': 'खाना पकाने को एक आनंददायक और उपयोगी अनुभव बनाएं।',
    'ar': 'حوّل تجربة الطهي إلى رحلة ممتعة ومفيدة.',
  },
  'Let’s start by answering a few quick questions about your cooking habits and preferences.': {
    'es':
        'Empecemos con unas preguntas sobre tus hábitos y preferencias al cocinar.',
    'fr':
        'Commençons par quelques questions sur vos habitudes et préférences culinaires.',
    'zh': '先回答几个关于烹饪习惯和偏好的问题吧。',
    'hi': 'खाना पकाने की आदतों और पसंद के बारे में कुछ सवालों से शुरू करें।',
    'ar': 'لنبدأ ببعض الأسئلة عن عاداتك وتفضيلاتك في الطهي.',
  },
  'Get Started': {
    'es': 'Empezar',
    'fr': 'Commencer',
    'zh': '开始',
    'hi': 'शुरू करें',
    'ar': 'ابدأ',
  },
  'Show me recipes': {
    'es': 'Ver recetas',
    'fr': 'Afficher les recettes',
    'zh': '查看食谱',
    'hi': 'रेसिपी दिखाएं',
    'ar': 'اعرض الوصفات',
  },
  'Continue': {
    'es': 'Continuar',
    'fr': 'Continuer',
    'zh': '继续',
    'hi': 'जारी रखें',
    'ar': 'متابعة',
  },
  'What is your cooking level?': {
    'es': '¿Cuál es tu nivel de cocina?',
    'fr': 'Quel est votre niveau en cuisine ?',
    'zh': '你的烹饪水平如何？',
    'hi': 'आपका खाना पकाने का स्तर क्या है?',
    'ar': 'ما مستوى خبرتك في الطهي؟',
  },
  'How much time do you have?': {
    'es': '¿Cuánto tiempo tienes?',
    'fr': 'De combien de temps disposez-vous ?',
    'zh': '你有多少时间？',
    'hi': 'आपके पास कितना समय है?',
    'ar': 'كم من الوقت لديك؟',
  },
  'What kind of food do you prefer?': {
    'es': '¿Qué tipo de comida prefieres?',
    'fr': 'Quel type de cuisine préférez-vous ?',
    'zh': '你喜欢哪种食物？',
    'hi': 'आपको किस तरह का खाना पसंद है?',
    'ar': 'ما نوع الطعام الذي تفضله؟',
  },
  'You can change these preferences any time.': {
    'es': 'Puedes cambiar estas preferencias cuando quieras.',
    'fr': 'Vous pouvez modifier ces préférences à tout moment.',
    'zh': '你可以随时更改这些偏好。',
    'hi': 'आप इन प्राथमिकताओं को कभी भी बदल सकते हैं।',
    'ar': 'يمكنك تغيير هذه التفضيلات في أي وقت.',
  },
  'Beginner': {
    'es': 'Principiante',
    'fr': 'Débutant',
    'zh': '初学者',
    'hi': 'शुरुआती',
    'ar': 'مبتدئ',
  },
  'Home cook': {
    'es': 'Cocinero aficionado',
    'fr': 'Cuisine familiale',
    'zh': '家常烹饪',
    'hi': 'घरेलू रसोइया',
    'ar': 'طاهٍ منزلي',
  },
  'Confident': {
    'es': 'Avanzado',
    'fr': 'À l’aise',
    'zh': '熟练',
    'hi': 'आत्मविश्वासी',
    'ar': 'متمكن',
  },
  'I am learning the basics': {
    'es': 'Estoy aprendiendo lo básico',
    'fr': 'J’apprends les bases',
    'zh': '我正在学习基础知识',
    'hi': 'मैं बुनियादी बातें सीख रहा/रही हूँ',
    'ar': 'أتعلم الأساسيات',
  },
  'I cook familiar meals': {
    'es': 'Cocino platos que ya conozco',
    'fr': 'Je cuisine des plats familiers',
    'zh': '我会做熟悉的菜',
    'hi': 'मैं परिचित व्यंजन बनाता/बनाती हूँ',
    'ar': 'أطبخ أطباقًا مألوفة',
  },
  'I enjoy trying new techniques': {
    'es': 'Me gusta probar técnicas nuevas',
    'fr': 'J’aime essayer de nouvelles techniques',
    'zh': '我喜欢尝试新技巧',
    'hi': 'मुझे नई तकनीकें आज़माना पसंद है',
    'ar': 'أحب تجربة تقنيات جديدة',
  },
  'Under 20 min': {
    'es': 'Menos de 20 min',
    'fr': 'Moins de 20 min',
    'zh': '20分钟以内',
    'hi': '20 मिनट से कम',
    'ar': 'أقل من 20 دقيقة',
  },
  'Under 45 min': {
    'es': 'Menos de 45 min',
    'fr': 'Moins de 45 min',
    'zh': '45分钟以内',
    'hi': '45 मिनट से कम',
    'ar': 'أقل من 45 دقيقة',
  },
  'Any time': {
    'es': 'Cualquier duración',
    'fr': 'Sans limite',
    'zh': '不限时间',
    'hi': 'कोई भी समय',
    'ar': 'أي مدة',
  },
  'Quick recipes': {
    'es': 'Recetas rápidas',
    'fr': 'Recettes rapides',
    'zh': '快捷食谱',
    'hi': 'जल्दी बनने वाली रेसिपी',
    'ar': 'وصفات سريعة',
  },
  'A little more time': {
    'es': 'Un poco más de tiempo',
    'fr': 'Un peu plus de temps',
    'zh': '多花一点时间',
    'hi': 'थोड़ा अधिक समय',
    'ar': 'وقت أطول قليلًا',
  },
  'No time limit': {
    'es': 'Sin límite de tiempo',
    'fr': 'Sans limite de temps',
    'zh': '时间不限',
    'hi': 'समय की कोई सीमा नहीं',
    'ar': 'لا يوجد حد زمني',
  },
  'No preference': {
    'es': 'Sin preferencias',
    'fr': 'Aucune préférence',
    'zh': '没有偏好',
    'hi': 'कोई पसंद नहीं',
    'ar': 'بلا تفضيل',
  },
  'Show all recipes': {
    'es': 'Mostrar todas las recetas',
    'fr': 'Afficher toutes les recettes',
    'zh': '显示所有食谱',
    'hi': 'सभी रेसिपी दिखाएं',
    'ar': 'اعرض كل الوصفات',
  },
  'Vegetarian': {
    'es': 'Vegetariano',
    'fr': 'Végétarien',
    'zh': '素食',
    'hi': 'शाकाहारी',
    'ar': 'نباتي',
  },
  'Vegan': {
    'es': 'Vegano',
    'fr': 'Végétalien',
    'zh': '纯素',
    'hi': 'वीगन',
    'ar': 'نباتي صرف',
  },
  'Plant-forward ideas': {
    'es': 'Ideas con más vegetales',
    'fr': 'Idées riches en végétaux',
    'zh': '以植物为主的创意',
    'hi': 'पौधों पर आधारित सुझाव',
    'ar': 'أفكار تعتمد على النباتات',
  },
  'Plant-based recipes': {
    'es': 'Recetas vegetales',
    'fr': 'Recettes végétales',
    'zh': '植物性食谱',
    'hi': 'पौधों पर आधारित रेसिपी',
    'ar': 'وصفات نباتية',
  },
  'Popular Categories': {
    'es': 'Categorías populares',
    'fr': 'Catégories populaires',
    'zh': '热门类别',
    'hi': 'लोकप्रिय श्रेणियाँ',
    'ar': 'فئات شائعة',
  },
  'Explore by country': {
    'es': 'Explorar por país',
    'fr': 'Explorer par pays',
    'zh': '按国家探索',
    'hi': 'देश के अनुसार देखें',
    'ar': 'استكشف حسب البلد',
  },
  'Recipes from': {
    'es': 'Recetas de',
    'fr': 'Recettes de',
    'zh': '来自此地的食谱：',
    'hi': 'यहाँ के व्यंजन:',
    'ar': 'وصفات من',
  },
  'Search results': {
    'es': 'Resultados de búsqueda',
    'fr': 'Résultats de recherche',
    'zh': '搜索结果',
    'hi': 'खोज परिणाम',
    'ar': 'نتائج البحث',
  },
  'Discover': {
    'es': 'Descubrir',
    'fr': 'Découvrir',
    'zh': '发现',
    'hi': 'खोजें',
    'ar': 'اكتشف',
  },
  'Search recipes around the world': {
    'es': 'Buscar recetas de todo el mundo',
    'fr': 'Rechercher des recettes du monde entier',
    'zh': '搜索世界各地的食谱',
    'hi': 'दुनिया भर की रेसिपी खोजें',
    'ar': 'ابحث عن وصفات من العالم',
  },
  'Filter recipes by calories': {
    'es': 'Filtrar recetas por calorías',
    'fr': 'Filtrer par calories',
    'zh': '按热量筛选食谱',
    'hi': 'कैलोरी के अनुसार छाँटें',
    'ar': 'تصفية الوصفات حسب السعرات',
  },
  'View ingredients & method': {
    'es': 'Ver ingredientes y preparación',
    'fr': 'Voir les ingrédients et la préparation',
    'zh': '查看食材和做法',
    'hi': 'सामग्री और विधि देखें',
    'ar': 'عرض المكونات وطريقة التحضير',
  },
  'Filter by estimated calories': {
    'es': 'Filtrar por calorías estimadas',
    'fr': 'Filtrer selon les calories estimées',
    'zh': '按估算热量筛选',
    'hi': 'अनुमानित कैलोरी के अनुसार छाँटें',
    'ar': 'تصفية حسب السعرات المقدرة',
  },
  'Recipes without nutrition labels use a rough category estimate.': {
    'es': 'Las recetas sin datos nutricionales usan una estimación general.',
    'fr': 'Une estimation est utilisée sans données nutritionnelles.',
    'zh': '没有营养标签的食谱使用类别估算值。',
    'hi': 'पोषण जानकारी न होने पर श्रेणी का अनुमान दिखाया जाता है।',
    'ar': 'تستخدم الوصفات بلا بيانات غذائية تقديرًا تقريبيًا.',
  },
  'Enable calorie filter': {
    'es': 'Activar filtro de calorías',
    'fr': 'Activer le filtre calorique',
    'zh': '启用热量筛选',
    'hi': 'कैलोरी फ़िल्टर चालू करें',
    'ar': 'تفعيل تصفية السعرات',
  },
  'per serving': {
    'es': 'por porción',
    'fr': 'par portion',
    'zh': '每份',
    'hi': 'प्रति सर्विंग',
    'ar': 'لكل حصة',
  },
  'Reset': {
    'es': 'Restablecer',
    'fr': 'Réinitialiser',
    'zh': '重置',
    'hi': 'रीसेट',
    'ar': 'إعادة ضبط',
  },
  'Show recipes': {
    'es': 'Ver recetas',
    'fr': 'Afficher les recettes',
    'zh': '显示食谱',
    'hi': 'रेसिपी दिखाएं',
    'ar': 'اعرض الوصفات',
  },
  'Retry': {
    'es': 'Reintentar',
    'fr': 'Réessayer',
    'zh': '重试',
    'hi': 'फिर कोशिश करें',
    'ar': 'أعد المحاولة',
  },
  'No favorite recipes yet.': {
    'es': 'Aún no tienes recetas favoritas.',
    'fr': 'Aucune recette favorite pour le moment.',
    'zh': '还没有收藏的食谱。',
    'hi': 'अभी कोई पसंदीदा रेसिपी नहीं है।',
    'ar': 'لا توجد وصفات مفضلة بعد.',
  },
  'No recipes found.': {
    'es': 'No se encontraron recetas.',
    'fr': 'Aucune recette trouvée.',
    'zh': '没有找到食谱。',
    'hi': 'कोई रेसिपी नहीं मिली।',
    'ar': 'لم يتم العثور على وصفات.',
  },
  'Recipe details are unavailable.': {
    'es': 'Los detalles no están disponibles.',
    'fr': 'Les détails de la recette sont indisponibles.',
    'zh': '暂时无法获取食谱详情。',
    'hi': 'रेसिपी का विवरण उपलब्ध नहीं है।',
    'ar': 'تفاصيل الوصفة غير متاحة.',
  },
  'Translating recipe…': {
    'es': 'Traduciendo receta…',
    'fr': 'Traduction de la recette…',
    'zh': '正在翻译食谱…',
    'hi': 'रेसिपी का अनुवाद हो रहा है…',
    'ar': 'جارٍ ترجمة الوصفة…',
  },
  'Ingredients': {
    'es': 'Ingredientes',
    'fr': 'Ingrédients',
    'zh': '食材',
    'hi': 'सामग्री',
    'ar': 'المكونات',
  },
  'Cooking steps': {
    'es': 'Pasos de preparación',
    'fr': 'Étapes de préparation',
    'zh': '烹饪步骤',
    'hi': 'पकाने के चरण',
    'ar': 'خطوات الطهي',
  },
  'Source': {
    'es': 'Fuente',
    'fr': 'Source',
    'zh': '来源',
    'hi': 'स्रोत',
    'ar': 'المصدر',
  },
  'Add ingredients to basket': {
    'es': 'Añadir ingredientes a la cesta',
    'fr': 'Ajouter les ingrédients au panier',
    'zh': '将食材加入清单',
    'hi': 'सामग्री सूची में जोड़ें',
    'ar': 'أضف المكونات إلى السلة',
  },
  'Shopping basket': {
    'es': 'Lista de compras',
    'fr': 'Panier de courses',
    'zh': '购物清单',
    'hi': 'खरीदारी सूची',
    'ar': 'سلة التسوق',
  },
  'Clear': {
    'es': 'Vaciar',
    'fr': 'Vider',
    'zh': '清空',
    'hi': 'खाली करें',
    'ar': 'مسح',
  },
  'Add ingredients from a recipe to see them here.': {
    'es': 'Añade ingredientes de una receta para verlos aquí.',
    'fr': 'Ajoutez des ingrédients depuis une recette pour les voir ici.',
    'zh': '从食谱添加食材后，它们会显示在这里。',
    'hi': 'यहाँ देखने के लिए रेसिपी से सामग्री जोड़ें।',
    'ar': 'أضف مكونات من وصفة لتظهر هنا.',
  },
  'Recipe data by TheMealDB · nutrition values are not supplied for every recipe.': {
    'es':
        'Datos de TheMealDB · algunas recetas no incluyen valores nutricionales.',
    'fr':
        'Données TheMealDB · les valeurs nutritionnelles ne sont pas toujours disponibles.',
    'zh': '食谱来自 TheMealDB · 部分食谱未提供营养数据。',
    'hi': 'TheMealDB का डेटा · हर रेसिपी में पोषण जानकारी नहीं होती।',
    'ar': 'بيانات TheMealDB · قد لا تتوفر القيم الغذائية لكل وصفة.',
  },
  'Edit serving': {
    'es': 'Editar porción',
    'fr': 'Modifier la portion',
    'zh': '编辑份量',
    'hi': 'मात्रा बदलें',
    'ar': 'تعديل الحصة',
  },
  'Adjust the amount. Calories and macros scale with it.': {
    'es': 'Ajusta la cantidad; las calorías y macros se recalculan.',
    'fr': 'Modifiez la quantité : calories et macros seront recalculées.',
    'zh': '调整份量后，热量和营养素会按比例更新。',
    'hi': 'मात्रा बदलें; कैलोरी और मैक्रो उसी अनुपात में बदलेंगे।',
    'ar': 'عدّل الكمية وستتغير السعرات والعناصر الغذائية معها.',
  },
  'Amount': {
    'es': 'Cantidad',
    'fr': 'Quantité',
    'zh': '数量',
    'hi': 'मात्रा',
    'ar': 'الكمية',
  },
  'Unit': {
    'es': 'Unidad',
    'fr': 'Unité',
    'zh': '单位',
    'hi': 'इकाई',
    'ar': 'الوحدة',
  },
  'Approximate weight': {
    'es': 'Peso aproximado',
    'fr': 'Poids approximatif',
    'zh': '估计重量',
    'hi': 'अनुमानित वज़न',
    'ar': 'الوزن التقريبي',
  },
  'Save changes': {
    'es': 'Guardar cambios',
    'fr': 'Enregistrer',
    'zh': '保存更改',
    'hi': 'बदलाव सहेजें',
    'ar': 'حفظ التغييرات',
  },
  'Could not save the serving change.': {
    'es': 'No se pudo guardar la porción.',
    'fr': 'Impossible d’enregistrer la portion.',
    'zh': '无法保存份量更改。',
    'hi': 'मात्रा में बदलाव सहेजा नहीं जा सका।',
    'ar': 'تعذر حفظ تغيير الحصة.',
  },
  'Eggs': {'es': 'Huevos', 'fr': 'Œufs', 'zh': '鸡蛋', 'hi': 'अंडे', 'ar': 'بيض'},
  'Pieces': {
    'es': 'Unidades',
    'fr': 'Pièces',
    'zh': '个/块',
    'hi': 'टुकड़े',
    'ar': 'قطع',
  },
  'Serving': {
    'es': 'Porción',
    'fr': 'Portion',
    'zh': '份',
    'hi': 'सर्विंग',
    'ar': 'حصة',
  },
  'Cup': {'es': 'Taza', 'fr': 'Tasse', 'zh': '杯', 'hi': 'कप', 'ar': 'كوب'},
  'No food logged yet.': {
    'es': 'Aún no hay alimentos registrados.',
    'fr': 'Aucun aliment enregistré.',
    'zh': '还没有记录食物。',
    'hi': 'अभी कोई खाना दर्ज नहीं है।',
    'ar': 'لم يتم تسجيل طعام بعد.',
  },
  'No meals recorded for this day.': {
    'es': 'No hay comidas registradas este día.',
    'fr': 'Aucun repas enregistré ce jour-là.',
    'zh': '当天没有记录餐食。',
    'hi': 'इस दिन कोई भोजन दर्ज नहीं है।',
    'ar': 'لا توجد وجبات مسجلة لهذا اليوم.',
  },
  'Chicken': {
    'es': 'Pollo',
    'fr': 'Poulet',
    'zh': '鸡肉',
    'hi': 'चिकन',
    'ar': 'دجاج',
  },
  'Seafood': {
    'es': 'Mariscos',
    'fr': 'Fruits de mer',
    'zh': '海鲜',
    'hi': 'समुद्री भोजन',
    'ar': 'مأكولات بحرية',
  },
  'My Favorites': {
    'es': 'Mis favoritos',
    'fr': 'Mes favoris',
    'zh': '我的收藏',
    'hi': 'मेरे पसंदीदा',
    'ar': 'مفضلاتي',
  },
  'Recipe translation is unavailable; showing the original text.': {
    'es': 'La traducción no está disponible; se muestra el texto original.',
    'fr': 'Traduction indisponible ; le texte original est affiché.',
    'zh': '暂时无法翻译，当前显示原文。',
    'hi': 'अनुवाद उपलब्ध नहीं है; मूल सामग्री दिखाई जा रही है।',
    'ar': 'الترجمة غير متاحة؛ يتم عرض النص الأصلي.',
  },
  'Recipe instructions provided by TheMealDB. Nutrition information may not be available.': {
    'es':
        'Instrucciones de TheMealDB. Puede que no haya información nutricional.',
    'fr':
        'Instructions de TheMealDB. Les informations nutritionnelles peuvent manquer.',
    'zh': '烹饪说明来自 TheMealDB。营养信息可能暂缺。',
    'hi': 'निर्देश TheMealDB से हैं। पोषण जानकारी उपलब्ध न भी हो सकती है।',
    'ar': 'تعليمات TheMealDB. قد لا تتوفر معلومات التغذية.',
  },
  'Tablespoons': {
    'es': 'Cucharadas',
    'fr': 'Cuillères à soupe',
    'zh': '汤匙',
    'hi': 'बड़े चम्मच',
    'ar': 'ملاعق كبيرة',
  },
  'Teaspoons': {
    'es': 'Cucharaditas',
    'fr': 'Cuillères à café',
    'zh': '茶匙',
    'hi': 'छोटे चम्मच',
    'ar': 'ملاعق صغيرة',
  },
  'American': {
    'es': 'Estadounidense',
    'fr': 'Américaine',
    'zh': '美国',
    'hi': 'अमेरिकी',
    'ar': 'أمريكي',
  },
  'British': {
    'es': 'Británica',
    'fr': 'Britannique',
    'zh': '英国',
    'hi': 'ब्रिटिश',
    'ar': 'بريطاني',
  },
  'Canadian': {
    'es': 'Canadiense',
    'fr': 'Canadienne',
    'zh': '加拿大',
    'hi': 'कनाडाई',
    'ar': 'كندي',
  },
  'Chinese': {
    'es': 'China',
    'fr': 'Chinoise',
    'zh': '中国',
    'hi': 'चीनी',
    'ar': 'صيني',
  },
  'Croatian': {
    'es': 'Croata',
    'fr': 'Croate',
    'zh': '克罗地亚',
    'hi': 'क्रोएशियाई',
    'ar': 'كرواتي',
  },
  'Dutch': {
    'es': 'Neerlandesa',
    'fr': 'Néerlandaise',
    'zh': '荷兰',
    'hi': 'डच',
    'ar': 'هولندي',
  },
  'Egyptian': {
    'es': 'Egipcia',
    'fr': 'Égyptienne',
    'zh': '埃及',
    'hi': 'मिस्री',
    'ar': 'مصري',
  },
  'Filipino': {
    'es': 'Filipina',
    'fr': 'Philippine',
    'zh': '菲律宾',
    'hi': 'फ़िलिपीनो',
    'ar': 'فلبيني',
  },
  'French': {
    'es': 'Francesa',
    'fr': 'Française',
    'zh': '法国',
    'hi': 'फ़्रांसीसी',
    'ar': 'فرنسي',
  },
  'Greek': {
    'es': 'Griega',
    'fr': 'Grecque',
    'zh': '希腊',
    'hi': 'यूनानी',
    'ar': 'يوناني',
  },
  'Indian': {
    'es': 'India',
    'fr': 'Indienne',
    'zh': '印度',
    'hi': 'भारतीय',
    'ar': 'هندي',
  },
  'Irish': {
    'es': 'Irlandesa',
    'fr': 'Irlandaise',
    'zh': '爱尔兰',
    'hi': 'आयरिश',
    'ar': 'أيرلندي',
  },
  'Italian': {
    'es': 'Italiana',
    'fr': 'Italienne',
    'zh': '意大利',
    'hi': 'इतालवी',
    'ar': 'إيطالي',
  },
  'Jamaican': {
    'es': 'Jamaiquina',
    'fr': 'Jamaïcaine',
    'zh': '牙买加',
    'hi': 'जमैका',
    'ar': 'جامايكي',
  },
  'Japanese': {
    'es': 'Japonesa',
    'fr': 'Japonaise',
    'zh': '日本',
    'hi': 'जापानी',
    'ar': 'ياباني',
  },
  'Kenyan': {
    'es': 'Keniana',
    'fr': 'Kényane',
    'zh': '肯尼亚',
    'hi': 'केन्याई',
    'ar': 'كيني',
  },
  'Malaysian': {
    'es': 'Malasia',
    'fr': 'Malaisienne',
    'zh': '马来西亚',
    'hi': 'मलेशियाई',
    'ar': 'ماليزي',
  },
  'Mexican': {
    'es': 'Mexicana',
    'fr': 'Mexicaine',
    'zh': '墨西哥',
    'hi': 'मैक्सिकन',
    'ar': 'مكسيكي',
  },
  'Moroccan': {
    'es': 'Marroquí',
    'fr': 'Marocaine',
    'zh': '摩洛哥',
    'hi': 'मोरक्को',
    'ar': 'مغربي',
  },
  'Polish': {
    'es': 'Polaca',
    'fr': 'Polonaise',
    'zh': '波兰',
    'hi': 'पोलिश',
    'ar': 'بولندي',
  },
  'Portuguese': {
    'es': 'Portuguesa',
    'fr': 'Portugaise',
    'zh': '葡萄牙',
    'hi': 'पुर्तगाली',
    'ar': 'برتغالي',
  },
  'Russian': {
    'es': 'Rusa',
    'fr': 'Russe',
    'zh': '俄罗斯',
    'hi': 'रूसी',
    'ar': 'روسي',
  },
  'Spanish': {
    'es': 'Española',
    'fr': 'Espagnole',
    'zh': '西班牙',
    'hi': 'स्पेनिश',
    'ar': 'إسباني',
  },
  'Thai': {
    'es': 'Tailandesa',
    'fr': 'Thaïlandaise',
    'zh': '泰国',
    'hi': 'थाई',
    'ar': 'تايلاندي',
  },
  'Tunisian': {
    'es': 'Tunecina',
    'fr': 'Tunisienne',
    'zh': '突尼斯',
    'hi': 'ट्यूनीशियाई',
    'ar': 'تونسي',
  },
  'Turkish': {
    'es': 'Turca',
    'fr': 'Turque',
    'zh': '土耳其',
    'hi': 'तुर्की',
    'ar': 'تركي',
  },
  'Ukrainian': {
    'es': 'Ucraniana',
    'fr': 'Ukrainienne',
    'zh': '乌克兰',
    'hi': 'यूक्रेनी',
    'ar': 'أوكراني',
  },
  'Vietnamese': {
    'es': 'Vietnamita',
    'fr': 'Vietnamienne',
    'zh': '越南',
    'hi': 'वियतनामी',
    'ar': 'فيتنامي',
  },
  'Could not reach the recipe catalog. Check your internet connection.': {
    'es': 'No se pudo conectar al catálogo. Comprueba tu conexión a Internet.',
    'fr': 'Impossible de joindre le catalogue. Vérifiez votre connexion Internet.',
    'zh': '无法连接食谱目录，请检查网络连接。',
    'hi': 'रेसिपी सूची से कनेक्ट नहीं हो सका। इंटरनेट कनेक्शन जाँचें।',
    'ar': 'تعذر الوصول إلى قائمة الوصفات. تحقق من اتصال الإنترنت.',
  },
  'Could not load these recipes. Try again.': {
    'es': 'No se pudieron cargar estas recetas. Inténtalo de nuevo.',
    'fr': 'Impossible de charger ces recettes. Réessayez.',
    'zh': '无法加载这些食谱，请重试。',
    'hi': 'ये रेसिपी लोड नहीं हो सकीं। फिर कोशिश करें।',
    'ar': 'تعذر تحميل هذه الوصفات. حاول مرة أخرى.',
  },
  'Could not load this category. Try again.': {
    'es': 'No se pudo cargar esta categoría. Inténtalo de nuevo.',
    'fr': 'Impossible de charger cette catégorie. Réessayez.',
    'zh': '无法加载此类别，请重试。',
    'hi': 'यह श्रेणी लोड नहीं हो सकी। फिर कोशिश करें।',
    'ar': 'تعذر تحميل هذه الفئة. حاول مرة أخرى.',
  },
  'Online search is temporarily unavailable.': {
    'es': 'La búsqueda en línea no está disponible temporalmente.',
    'fr': 'La recherche en ligne est temporairement indisponible.',
    'zh': '在线搜索暂时不可用。',
    'hi': 'ऑनलाइन खोज अभी उपलब्ध नहीं है।',
    'ar': 'البحث عبر الإنترنت غير متاح مؤقتًا.',
  },
};
